### ISSUE TITLE
In readme.md add an example of actually using the created message with net/smtp

### ISSUE THREAD

**Issue by elviejo79** [marcw/ezmail#1]
It's a small thing but on the readme.md
I thin it needs an example of actually using the generated email
with the net/smtp package from Go.

TIA

**Comment by marcw** [comment]
You're right. I'm gonna do this right now.

**Comment by marcw** [comment]
Here you are. Hope you'll have fun.

**Comment by elviejo79** [comment]
Thanks :-)
