### ISSUE TITLE
msg.Recipients() returns "invalid" format at least for gmail.

### ISSUE THREAD

**Issue by elviejo79** [marcw/ezmail#2]
when sending a message with gmail like this:

err = smtp.SendMail("smtp.gmail.com:587", auth, msg.From.Address, msg.Recipients(), msg.Bytes())

gmail will send an error:
response: 5.5.2 Syntax error. dh7sm475597vdb.0 - gsmtp

I think the error is that msg.Recipients() returns:
 []string{"agarcia@example.com"}

However smtp.SendMail expects
[]string{"agarcia@example.com"} 

without the "<" ">"

**Comment by marcw** [comment]
Is it possible for you to check with another smtp server?
